choice = 0
while choice != 1:
	print ('Welcome to this Nokia menu map ')
	print('1 - Phone book')
	print('2 - Messages')
	print('3 - Chat')
	print('4 - Call register')
	print('5 - Tones')
	print('6 - Settings')
	print('7 - Call divert')
	print('8 - Games')
	print('9 - Calculator')
	print('10 - Reminders')
	print('11 - Clock')
	print('12 - Profiles')
	print('13 - SIM services')	
	match choice:
		case 1:
			print("====Phone book====")
			print("1. Search")
			print("2. Service Nos")
			print("3. Add name")
			print("4. Erase")
			print("5. Edit")
			print("6. Assign Tone")
			print("7. Send b' card")
			print("8. Options")
			print("	1. Type of view")
			print("	2. Memory status")
			print("9. Speed dials")
			print("10. Voice tags")
		
		case 2:
			print("====Messages====")
			print("1. Write messages")
			print("2. Inbox")
			print("3. Outbox")
			print("4. Picture messages")
			print("5. Templates")
			print("6. Smileys")
			print("7. Messages settngs")
			print("	1. Set 1")
			print("	1. Message centre number")
		print("	2. Message sent as")
		print("	3. Message validity")
		print("	2. Common")
		print("	1. Delivery reports")
		print("	2. Reply via same centre")
		print("	3. Character support")
		print("8. Info service")
		print("9. Voice mailbox number")
		print("10. Service command editor")
	case 3:
		print("Chat")
	case 4:
		print("====Call register====")
		print("1. Missed calls")
		print("2. Received calls")
		print("3. Dialled numbers")
		print("4. Erase recent call lists")
		print("5. Show call duration")
		print("	1. Last call duration")
		print("	2. All call's duration")
		print("	3. Received call's duration")
		print("	4. Dialled call's duration")
		print("	5. Clear timers")
		print("6. Show call cost")
		print("	1. Last call's cost")
		print("	2. All call's cost")
		print("	3. Clear counters")
		print("7. Cost call settings")
		print("	1. Call cost limit")
		print("	2. Show cost in")
		print("8. Prepaid credit")

	case 5:
		print("====Tones====")
		print("1. Ringing tone")
		print("2. Ringing volume")
		print("3. Incoming call alert")
		print("4. Composer")
		print("5. Message alert tone")
		print("6. Keypad tones")
		print("7. Warning and game tones")
		print("8. Vibrating alert")
		print("9. Screen saver")
	case 6:
		print("====Settings====")
		print("Call settings")
		print("	1. Automatic redial")
		print("	2. Speed dialing")
		print("	3. Call waiting action")
		print("	4. Own number sending")
		print("	5. Phone line in use")
		print("	6. Automatic answer")
		print("Phone settings")
		print("	1. Language")
		print("	2. Cell info display")
		print("	3. Welcome note")
		print("	4. Network selection")
		print("	5. Lights")
		print("	6. Condirm SIM service actions")
		print("Security settings")
		print("	1. PIN code request")
		print("	2. Call barring service")
		print("	3. Fixed dialing")
		print("	4. Closed user group")
		print("	5. Phone security")
		print("	6. Change access codes")
		print("4. Rsetore factory settings")
	case 7:
		print("1. Call divert")
	case 8:
		print("1. Games")
	case 9:
		print("1. Calculator")
	case 10:
		print("1. Reminders")
	case 11:
		print("====Clock====")
		print("1. Alarm clock")
		print("2. Clock settings")
		print("3. Date settings")
		print("4. Stopwatch")
		print("5. Countdown timer")
		print("6. Auto update of date and time")
			
	case 12:
		print("1. Profiles")
	case 13:
		print("1. SIM services")
	case _:
		print("Au revoir!!!")
		